### ISSUE TITLE
About requirements and environment

### ISSUE THREAD

**Issue by mseok** [THGLab/PDBBind-Opt#1]
Thank you for great work!

I want to request about requirements and environments files for using the processing code.
It would be helpful to others to make data from scratch.

Thanks

**Comment by KSUN63** [comment]
Thanks for your suggestion! We can definitely come up with a section for env setup.

As for a quick response, we used pretty much all the standard cheminformatic packages for the bulk of the code, including numpy, scipy, pandas, rdkit, biopython, openmm, pdbfixer, and openforcefield. Let me know if you run into any problems!

**Comment by mseok** [comment]
Thank you.
I can now run the scripts normally.

**Comment by KSUN63** [comment]
Awesome! I personally have very limited experience with mamba. If you don't mind creating a pull request to update the procedures of setting up the environment with mamba, please go ahead and do so. Our team will greatly appreciate your effort :) Thanks in advance

- Oliver
