### ISSUE TITLE
Clarification on chain selection in `*_protein_refined.pdb` files

### ISSUE THREAD

**Issue by wehs7661** [THGLab/PDBBind-Opt#2]
Thanks a lot for the great work in addressing some very important issues in PDBbind!

I have just one quick question. I understand that one strength PDBbind-Opt introduces is that it splits any records that have ligands bound to different chains with the same sequence into multiple records. However, it is not entirely clear to me what chains get deposited in the final `*_protein_refined.pdb`.

For example, for PDB entry `1a1e`, there are subfolders including `1a1e_ACE-DIY_C_100-103` and `1a1e_ACE-DIY_D_100-103`. Initially, I assumed that the refined PDB file in the former would contain only chain A (which the ligand chain C binds to), and the refined PDB file in the latter would contain only chain B (which the ligand chain D binds to). However, I observed that while the refined PDB file in the second directory indeed only contained chain B, the refined PDB file in the first directory included both chains A and B.

I might be missing something from the paper, but could you clarify the criteria used to decide which chains are included in the `*_protein_refined.pdb` files? Thanks so much!

**Comment by KSUN63** [comment]
Hi Wei-Tse,

Thanks for your question! We used the same cutoff distance as PDBBind (10A) to select protein chains for a certain ligand. In other words, if a protein chain contain at least an atom that are less than 10A away from the ligand, we will include them. The reason behind this is that some ligands bind to the interface between protein chains and it doesn't make a lot of sense to keep only one chain in those scenarios.

Best,
Oliver

**Comment by wehs7661** [comment]
Hi Oliver, 
That makes sense. Thanks a lot for the provided details! I'm closing the issue now. 

Best,
Wei-Tse
