### ISSUE TITLE
"-d" is a typo, right? in the process.py usage

### ISSUE THREAD

**Issue by Huilin-Li** [THGLab/PDBBind-Opt#3]
In the usage steps, I see `python process.py -i xxx -d xxx`. The `-d` should be `-o` ,right?

**Comment by KSUN63** [comment]
Hi Huilin,

Thanks for pointing it out! You are most definitely right that in the current code the flag should be -o. I'll change the code to make it consistent with the README file to avoid any confusion and keep it consistent with the flag of gather.py. Will close this issue now.

Best,
Oliver
