### ISSUE TITLE
Are they expected to occur?: did not recognize residue LYS; Inferred from InChI

### ISSUE THREAD

**Issue by Huilin-Li** [THGLab/PDBBind-Opt#4]
Hi, thanks for your great work.

I am new in this area, and when I execute `python procees.py -i ../pre_process/PDBBind_poly.csv -o ../raw_data/pdbbind_opt_poly --poly`, I got this,

![image](https://github.com/user-attachments/assets/5b520e1c-f220-46fd-aec2-96741d127b25)

when I execute `python procees.py -i ../pre_process/PDBBind_sm.csv -o ../raw_data/pdbbind_opt_sm`, I got this,
![image](https://github.com/user-attachments/assets/49d79583-b39d-43c1-805a-957744f6f81d)

Are they expected to occur?

**Comment by Ericwang6** [comment]
Hi huilin, yes they are expected to occur
